# Generated by Django 4.2.1 on 2023-06-08 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCiudad', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuponDescuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_cupon', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('id_status', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=50)),
                ('indicativo', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EstadodeCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_compra', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormadePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formas_pago', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePais', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSubCategoria', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenProfile', models.ImageField(blank=True, null=True, upload_to='profile/', validators=[shop.models.validate_imagenProfile_resolution])),
                ('telephone_number', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ciudades')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.departamentos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/', validators=[shop.models.validate_image_resolution])),
                ('precio', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_categoria', models.ManyToManyField(to='shop.categoria')),
                ('id_subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='OrdendeCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_cupon_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.cupondescuento')),
                ('id_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.descuento')),
                ('id_estado_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.estadodecompra')),
                ('id_forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.formadepago')),
                ('id_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.producto')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDescuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.descuento')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producto')),
            ],
        ),
        migrations.AddField(
            model_name='descuento',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producto'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pais'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.departamentos'),
        ),
    ]
