# Generated by Django 4.2.1 on 2023-05-27 16:17

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[shop.models.validate_image_resolution]),
        ),
    ]
