# Generated by Django 4.2.1 on 2023-05-12 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ciudades_pais_domicilio_departamentos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuponDescuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_cupon', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('id_status', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EstadodeCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_compra', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormadePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formas_pago', models.CharField(max_length=50)),
                ('id_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='OrdendeCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.domicilio')),
                ('id_estado_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.estadodecompra')),
                ('id_forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formadepago')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDescuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.descuento')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.producto')),
            ],
        ),
        migrations.AddField(
            model_name='descuento',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.producto'),
        ),
    ]
