# Generated by Django 4.2.1 on 2023-05-13 01:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.subcategoria', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
